### ISSUE TITLE
Stack trace loading crate with more than one root dataset

### ISSUE THREAD

**Issue by marcolarosa** [UTS-eResearch/describo-online#4]
Error shows in log:
```
[10:36] Marco La Rosa
    Error: The crate does not have exactly one root dataset descriptor
    at e.value (/srv/server.bundle.js:1:59750)
    at e.value (/srv/server.bundle.js:1:59903)
    at e.<anonymous> (/srv/server.bundle.js:1:58047)
    at tryCatch (/srv/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/srv/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/srv/node_modules/regenerator-runtime/runtime.js:118:21)
    at nr (/srv/server.bundle.js:1:57117)
    at i (/srv/server.bundle.js:1:57321)
2020-11-30T23:32:59.667Z ERROR: loadRouterHandler: The crate does not have exactly one root dataset descriptor
```

But doesn't make it back to user.

**Comment by marcolarosa** [comment]
fixed
